spring.application.name=payment-engine


spring.datasource.url=jdbc:mysql://localhost:3306/payment_engine
spring.datasource.username=root
spring.datasource.password=Fouzan@123#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

# =========================
# Kafka Configuration
# =========================

spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#spring.ai.mistralai.api-key=${MISTRAL_API_KEY}
#spring.ai.mistralai.chat.model=mistral-small-2603
#spring.ai.mistralai.chat.temperature=0.2

# OpenRouter
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api/v1

spring.ai.openai.chat.model=google/gemma-4-26b-a4b-it
spring.ai.openai.chat.temperature=0.2

spring.ai.retry.max-attempts=2
spring.ai.retry.backoff.initial-interval=5s
spring.ai.retry.backoff.multiplier=2
spring.ai.retry.backoff.max-interval=30s

jwt.secret=${JWT_SECRET}

# ===============================
# Spring Boot Actuator
# ===============================

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true

info.app.name=Payment Processing and Fraud Detection Engine
info.app.description=High-throughput payment processing system with fraud detection
info.app.version=1.0.0








